apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-backend
  template:
    metadata:
      labels:
        app: dental-backend
    spec:
      containers:
        - name: dental-backend
          image: cuencaharoldr/dental-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "dental-db2.cixqeq0einm3.us-east-1.rds.amazonaws.com"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "D1W2cfH87weqTtelqxic"
            - name: DB_NAME
              value: "dental"
